#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."
test_dir=$(mktemp -d)
trap 'rm -rf "$test_dir"' EXIT

for addon in SomfyProtect2MQTT SomfyProtect2MQTT-2nd-somfy-account SomfyProtect2MQTT-dev; do
    # Exercise the actual startup conversion without Home Assistant services.
    awk '
        /^echo.*Generated by homeassistant/ { copying = 1 }
        /^# Log configuration/ { copying = 0 }
        copying
    ' "$addon/rootfs/etc/s6-overlay/s6-rc.d/SomfyProtect2MQTT/run" |
        sed -e "s|/usr/bin/SomfyProtect2MQTT/somfyProtect2Mqtt/config|$test_dir|g" \
            -e "s|/data/options.json|$test_dir/options.json|g" > "$test_dir/generate.sh"

    for device_macs in '[]' \
        '[{"device":"Badge","mac":"AA:BB:CC:DD:EE:FF"},{"device":"Badge 2","mac":"11:22:33:44:55:66"}]' \
        '{"Badge":"AA:BB:CC:DD:EE:FF","Badge 2":"11:22:33:44:55:66"}' \
        'null'; do
        printf 'somfy_protect:\n  sites: [Maison, Bureau]\nhomeassistant_config:\n  code: "0012"\n  device_macs: %s\n' \
            "$device_macs" | yq -o=json > "$test_dir/options.json"
        if [[ "$device_macs" == null ]]; then
            yq -i -o=json 'del(.homeassistant_config.device_macs)' "$test_dir/options.json"
        fi
        bash "$test_dir/generate.sh"
        [[ $(yq -o=json -I=0 '.somfy_protect.sites' "$test_dir/config.yaml") == '["Maison","Bureau"]' ]]
        yq -e '.homeassistant_config.code == "0012" and (.homeassistant_config.code | type == "!!str")' \
            "$test_dir/config.yaml" > /dev/null
        case "$device_macs" in
            '[]') expected='{}' ;;
            null) expected='null' ;;
            *) expected='{"Badge":"AA:BB:CC:DD:EE:FF","Badge 2":"11:22:33:44:55:66"}' ;;
        esac
        [[ $(yq -o=json -I=0 '.homeassistant_config.device_macs' "$test_dir/config.yaml") == "$expected" ]]
    done
    echo "$addon: configuration conversion OK"
done
