---
# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: python:3.12-slim-bookworm
  amd64: python:3.12-slim-bookworm
  armhf: python:3.12-slim-bookworm
  armv7: python:3.12-slim-bookworm
  i386: python:3.12-slim-bookworm
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Minims add-on"
  org.opencontainers.image.description: "Minims add-on to use as a blueprint for new add-ons."
  org.opencontainers.image.source: "https://github.com/Minims/homeassistant-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  VERSION: "2025.12.0"
