---
# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/hassio-addons/base:16.3.6
  amd64: ghcr.io/hassio-addons/base:16.3.6
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: SomfyProtect2MQTT (dev)"
  org.opencontainers.image.description: "Publish Somfy Home Alarm as MQTT messages - Development branch."
  org.opencontainers.image.source: "https://github.com/Minims/homeassistant-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  VERSION: "2026.1.1"
