---
# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/hassio-addons/base:14.1.0
  amd64: ghcr.io/hassio-addons/base:14.1.0
  armhf: ghcr.io/hassio-addons/base:14.1.0
  armv7: ghcr.io/hassio-addons/base:14.1.0
  i386: ghcr.io/hassio-addons/base:14.1.0
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Minims add-on"
  org.opencontainers.image.description: "Minims add-on to use as a blueprint for new add-ons."
  org.opencontainers.image.source: "https://github.com/Minims/homeassistant-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  VERSION: "2023.10.1"
